---
- hosts: 'localhost'
  roles:
    - { role: gpu, nvidia_version: "470.57.02", tags: [ drivers, kernelupgrade, gpu,nvidia ] } # currently in https://gitlab.erc.monash.edu.au/hpc-team/HPCasCode will be enabled after sucessfull testing
    - { role: systemd-nvidia-uvm, tags: [ uvm,kernelupgrade,nvidia ] } # currently in https://gitlab.erc.monash.edu.au/hpc-team/HPCasCode will be enabled after sucessfull testing
    - { role: vncserver, tags: [ other, extra_packages ] } # includes mate desktop. maybe this should be renamed.
    - { role: singularity, singularity_version: "3.9.9",  become: yes, golang_version: "1.18.1", golang_redis_sha256sum: "b3b815f47ababac13810fc6021eb73d65478e0b2db4b09d348eefad9581a2334", tags: [ other, singularity ] }
    - { role: xorguserspace, tags: [ xorguserspace ] }
- hosts: 'localhost'
  tasks:
    - { name: Install virtualGl, apt: { deb: "https://swift.rc.nectar.org.au/v1/AUTH_810/CVL-Singularity-External-Files/virtualgl_2.6.2_amd64.deb"} ,become: true, tags: [vgl] }
    # TODO mount CVL-Software singularity containers
    # TODO setup desktop icons
    # TODO a simple test would be nice maybe tensorflow printing the first cudagpu

